### ISSUE TITLE
Newtonsoft.Json dependency required

### ISSUE THREAD

**Issue by brunochaina** [vese/Recaptcha.Verify.Net#4]
Hi,

I updated to version 2.1 running on .NET 7 and got the following error when calling _VerifyAsync(token)_:

`An error occurred deserializing the response. - An error occurred deserializing the response. - Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified`

I added a dependency to Newtonsoft.Json (installed the latest version, 13.0.3 at this time) and that fixed it. I think there is a missing dependency on Newtonsoft.Json in the Nuget package.

Thank you,

Bruno

**Comment by vese** [comment]
Hi, @brunochaina 
Thanks for the issue
Please check version 2.2 of package
Removed unnecessary Newtonsoft.Json referense
